# My Batis
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jobworld
    password: 1234
    sql:
      init:
        encoding: UTF-8

# Server
server:
  port: 8080
  servlet:
    session:
      timeout: 120m