
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sua_example
    password: 1234
    sql:
      init:
        encoding: UTF-8

# My Batis
mybatis:
  mapper-locations: classpath:mappers/**/*.xml

# Server
server:
  port: 8080
  servlet:
    session:
      timeout: 120m